In [66]:
import torch

checkpoint = torch.load('MNIST_ConvNetD3_GraNd_exp0_epoch1_1.0_9.800000.ckpt')
print(checkpoint.keys())


dict_keys(['exp', 'epoch', 'state_dict', 'opt_dict', 'best_acc1', 'rec', 'subset', 'sel_args'])


C:\Users\Paul\AppData\Local\Temp\ipykernel_53888\4262972630.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load('MNIST_ConvNetD3_GraNd_exp0_epoch1_1.

In [67]:
scores = checkpoint["subset"]['scores']
indices = checkpoint["subset"]['indices']

In [68]:
from torchvision import datasets, transforms
data_path = "./data_path"
channel = 1
im_size = (28, 28)
num_classes = 10
mean = [0.1307]
std = [0.3081]
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize(mean=mean, std=std)])
dst_train = datasets.MNIST(data_path, train=True, download=True, transform=transform) # no augmentation
dst_test = datasets.MNIST(data_path, train=False, download=True, transform=transform)
class_names = dst_train.classes
class_map = {x:x for x in range(num_classes)}
images_all = []
labels_all = []
indices_class = [[] for c in range(num_classes)]

In [69]:
images_all = [torch.unsqueeze(dst_train[i][0], dim=0) for i in range(len(dst_train))]
labels_all = [dst_train[i][1] for i in range(len(dst_train))]

In [70]:
for i, lab in enumerate(labels_all):
    indices_class[lab].append(i)

In [71]:
print("Number of images in the subset: ", len(indices))
print("Number of scores: ", len(scores))
print("Number of images in the dataset: ", len(dst_train))
print("Number of classes: ", num_classes)
print("Number of images per class: ", [len(indices_class[c]) for c in range(num_classes)])

Number of images in the subset:  60000
Number of scores:  60000
Number of images in the dataset:  60000
Number of classes:  10
Number of images per class:  [5923, 6742, 5958, 6131, 5842, 5421, 5918, 6265, 5851, 5949]


In [73]:
import torch

# Assuming `indices` and `scores` are lists or tensors containing the data for each label.
# Also assuming `indices_class` has been populated with the indices for each class.

sorted_tensors = []

for class_idx, class_indices in enumerate(indices_class):
    # Extract scores and indices for the current class
    class_scores = [scores[i] for i in class_indices]
    class_indices = [indices[i] for i in class_indices]
    
    # Sort the class indices based on scores in descending order
    sorted_pairs = sorted(zip(class_indices, class_scores), key=lambda x: x[1], reverse=True)
    sorted_indices = [pair[0] for pair in sorted_pairs]
    
    # Combine sorted indices and scores into a tensor
    length = len(sorted_indices)
    print("Class: ", class_idx, "Length: ", length)
    print("Sorted indices: ", sorted_indices)
    sorted_tensor = torch.tensor(sorted_indices)
    sorted_tensors.append(sorted_tensor)

torch.save(sorted_tensors, 'MNIST_ConvNet3.pt')


Class:  0 Length:  5923
Sorted indices:  [49507, 44602, 42089, 9928, 24500, 25013, 53117, 27740, 89, 23262, 53715, 54033, 35514, 22542, 2122, 14145, 18968, 56437, 62, 19258, 40150, 13257, 51413, 43224, 38209, 34129, 25164, 38186, 53110, 39854, 16293, 46973, 13736, 24303, 23927, 56993, 40465, 29432, 32831, 31187, 57145, 38997, 32570, 19414, 37476, 21184, 48043, 44114, 27398, 45904, 47911, 48961, 9350, 56899, 55332, 27356, 6598, 44763, 17669, 59176, 56177, 59733, 33964, 34516, 58002, 59443, 56167, 24218, 1595, 16760, 50525, 44119, 29744, 20984, 2357, 31734, 7967, 26677, 37910, 30728, 25053, 34797, 4517, 57207, 34456, 8326, 26940, 21648, 34442, 1704, 21348, 46700, 21136, 59909, 16923, 47019, 41329, 53849, 21551, 35308, 44635, 56389, 48094, 51636, 17024, 38108, 8462, 6395, 5599, 44935, 34421, 32658, 14324, 37777, 54337, 10331, 27025, 21203, 45343, 16033, 40638, 2888, 45237, 47310, 43120, 57758, 7218, 51485, 22582, 26845, 27662, 40283, 28815, 37587, 28581, 59346, 48275, 32, 57622, 23639, 90

In [76]:
sorted_tensors

[tensor([49507, 44602, 42089,  ...,  6587, 59106, 33351]),
 tensor([15233, 57419, 24808,  ..., 47269,  7012, 42705]),
 tensor([29987, 56379, 58032,  ..., 30611, 27472, 17181]),
 tensor([51000, 32494,   747,  ..., 32634,  7461,  8231]),
 tensor([19256, 32493, 26236,  ..., 43900, 52305, 15982]),
 tensor([38338, 12202, 15783,  ..., 22106, 36401, 57851]),
 tensor([30025, 20503, 50102,  ..., 19848,  2243, 22344]),
 tensor([ 2446, 46467, 59731,  ..., 41553, 25257, 19837]),
 tensor([36549, 18821, 20501,  ...,  4310,   583, 53142]),
 tensor([34273, 26051, 56477,  ..., 15515,  3152, 13467])]